[project]
name = "langgraph-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "michael-basweti", email = "baswetima@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipython>=9.16.1",
    "langchain-core>=1.5.5",
    "langchain-google-genai>=4.3.4",
    "langgraph>=1.2.11",
]

[project.scripts]
langgraph-tutorial = "langgraph_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
